---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: '10.20.1.101'}]
  vagrantfiles:
    - test/Files/Vagrant.Disk.rb

provisioner:
  name: chef_zero
  data_bags_path: ./test/fixtures/data_bags

platforms:
 - name: centos66-cloud-1.7.1

suites:
  - name: default
    run_list:
      - recipe[workflow::default]
    attributes:
